"""Build the Vakya browser extension for sharing.

    python desktop/build.py

- writes extension/config.js (server address + app key) from android/vakya.properties,
  so the desktop extension talks to the same server as the phone app;
- makes the icons from android/logo.png and copies the serif font;
- zips everything into release/Vakya-Desktop-<version>.zip.

config.js holds the app key, so it is git-ignored (like vakya.properties).
"""

from __future__ import annotations

import json
import shutil
import sys
import zipfile
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
EXT = ROOT / "desktop" / "extension"
PROPS = ROOT / "android" / "vakya.properties"
LOGO = ROOT / "android" / "logo.png"
FONT = ROOT / "android" / "app" / "src" / "main" / "res" / "font" / "instrument_serif.ttf"
RELEASE = ROOT / "release"

# Files that go into the zip (config.example.js and tests stay out).
SHIPPED = [
    "manifest.json", "background.js", "config.js", "shared.js", "content.js", "content.css",
    "options.html", "options.js",
    "icons/icon16.png", "icons/icon32.png", "icons/icon48.png", "icons/icon128.png",
    "fonts/instrument_serif.ttf",
]


def read_properties(path: Path) -> dict[str, str]:
    props = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            props[key.strip()] = value.strip()
    return props


def write_config() -> None:
    if not PROPS.exists():
        sys.exit(f"Missing {PROPS.relative_to(ROOT)} (it holds the server address and app key).")
    props = read_properties(PROPS)
    if not props.get("serverUrl"):
        sys.exit("vakya.properties has no serverUrl.")
    config = {"serverUrl": props["serverUrl"], "appKey": props.get("appKey", "")}
    (EXT / "config.js").write_text(
        "// Generated by desktop/build.py from android/vakya.properties. Don't commit.\n"
        f"self.VAKYA_CONFIG = {json.dumps(config, indent=2)};\n",
        encoding="utf-8",
    )


def _ink_box(gray: Image.Image, threshold: int = 200) -> tuple[int, int, int, int]:
    return gray.point(lambda p: 255 if p < threshold else 0).getbbox()


def _square(img: Image.Image, box: tuple[int, int, int, int], pad: float) -> Image.Image:
    """Centre [box] of [img] on a white square with [pad] (fraction of the side) around it."""
    left, top, right, bottom = box
    side = int(max(right - left, bottom - top) * (1 + 2 * pad))
    canvas = Image.new("RGB", (side, side), "white")
    canvas.paste(img.crop(box), ((side - (right - left)) // 2, (side - (bottom - top)) // 2))
    return canvas


def make_icons() -> None:
    logo = Image.open(LOGO).convert("RGB")
    gray = logo.convert("L")
    out = EXT / "icons"
    out.mkdir(exist_ok=True)

    # 48 and 128: the whole wordmark (it reads fine at these sizes).
    word = _square(logo, _ink_box(gray), pad=0.06)
    for size in (48, 128):
        word.resize((size, size), Image.LANCZOS).save(out / f"icon{size}.png", optimize=True)

    # 16 and 32 (toolbar): the wordmark is unreadable that small, so use the "v" alone:
    # flood-fill the shape that holds the leftmost ink and take its bounds.
    left, top, _, bottom = _ink_box(gray)
    ink = gray.point(lambda p: 255 if p < 200 else 0)
    seed = next((left, y) for y in range(top, bottom + 1) if ink.getpixel((left, y)))
    ImageDraw.floodfill(ink, seed, 128)
    v_mask = ink.point(lambda p: 255 if p == 128 else 0).filter(ImageFilter.MaxFilter(5))  # keep soft edges
    v_only = Image.composite(logo, Image.new("RGB", logo.size, "white"), v_mask)
    v = _square(v_only, v_mask.getbbox(), pad=0.12)
    for size in (16, 32):
        v.resize((size, size), Image.LANCZOS).save(out / f"icon{size}.png", optimize=True)


def copy_font() -> None:
    (EXT / "fonts").mkdir(exist_ok=True)
    shutil.copyfile(FONT, EXT / "fonts" / "instrument_serif.ttf")


def make_zip() -> Path:
    version = json.loads((EXT / "manifest.json").read_text(encoding="utf-8"))["version"]
    RELEASE.mkdir(exist_ok=True)
    target = RELEASE / f"Vakya-Desktop-{version}.zip"
    for old in RELEASE.glob("Vakya-Desktop-*.zip"):
        old.unlink()
    # Files at the zip's root: Windows "Extract All" already makes a folder named after the zip,
    # and that folder must hold manifest.json for "Load unpacked".
    with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED) as zf:
        for name in SHIPPED:
            zf.write(EXT / name, name)
        zf.write(ROOT / "android" / "third_party" / "InstrumentSerif-OFL.txt", "fonts/OFL.txt")
    # And an unzipped copy next to it for "Load unpacked". Same folder name every version,
    # so after a rebuild the reload button in chrome://extensions picks up the new code.
    unpacked = RELEASE / "Vakya-Desktop"
    for old in [unpacked, *RELEASE.glob("Vakya-Desktop-*")]:
        if old.is_dir():
            shutil.rmtree(old)
    with zipfile.ZipFile(target) as zf:
        zf.extractall(unpacked)
    return target


def main() -> None:
    write_config()
    make_icons()
    copy_font()
    target = make_zip()
    print(f"Built {target.relative_to(ROOT)} ({target.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
